import test from 'node:test';import assert from 'node:assert/strict';
import {extractCapturedPage} from '../crawler/captured-page.js';
import {extractEvent} from '../crawler/extract.js';
import {extractCivicMeeting} from '../crawler/civic.js';
const date='2026-10-08T12:00:00Z';
function fixture(patch={}){const event={'@type':'MusicEvent',name:'Test &amp; Band',startDate:'2026-11-06T21:00:00-06:00',location:{name:'Hall',address:{streetAddress:'1 Test St',addressLocality:'Bentonville',addressRegion:'AR'}},...patch};return {url:'https://themomentary.org/calendar/test/',status:'ok',fetchedAt:date,documents:[event],text:'Open today 10am - 6pm\nTest & Band\nMusic\nNOV 6, 8 PM (Doors at 7:30)\nGet Tickets\nFooter\nOther event NOV 7, 1 PM'}}
const target={title:'Test & Band',category:'music'};
test('HTML entities preserve identity and visible-vs-JSON-LD time conflict cannot become ready',()=>{const r=extractCapturedPage(fixture(),target);assert.ok(r.event);assert.ok(r.event.uncertainFields.includes('time'));assert.equal(r.complete,false);assert.match(r.event.evidence,/20:00.*21:00/);assert.doesNotMatch(r.event.research.snapshots[0].text,/Open today|Other event/)});
test('visible agreement excludes opening hours and doors and leaves end time unknown',()=>{const r=extractCapturedPage(fixture({startDate:'2026-11-06T20:00:00-06:00'}),target);assert.equal(r.event.time,'20:00');assert.equal(r.event.endTime,'');assert.equal(r.complete,true)});
test('name mismatch, duplicate title and blocked capture never merge into existing event',()=>{assert.equal(extractCapturedPage(fixture(),{title:'Other show'}).event,null);const c=fixture();c.documents.push(c.documents[0]);assert.equal(extractCapturedPage(c,target).event,null);assert.equal(extractCapturedPage({...c,status:'blocked'},target).event,null)});
test('description repeat day and finish contradict structured schedule',()=>{const c={url:'https://thenwatoday.com/events/test',status:'ok',fetchedAt:date,documents:[{'@type':'Event',name:'Art social',startDate:'2026-10-08T18:00:00-05:00',endDate:'2026-10-08T21:00:00-05:00',description:'Every 2nd & 4th Wednesday from 6~8pm.'}],text:'Art social\nWhen\nThursday, October 8 · 6:00 PM\nWhere\nStudio\nDetails\nRelated show'};const e=extractCapturedPage(c,{title:'Art social',category:'arts'}).event;assert.ok(e.uncertainFields.includes('date'));assert.ok(e.uncertainFields.includes('endTime'))});
test('structured ItemList events are visited, no unbounded page-wide regex',()=>{const c=fixture();const r=extractEvent({document:{'@type':'ItemList',itemListElement:[{item:c.documents[0]}]},expectedTitle:'Test & Band',url:c.url,allowedCities:['Bentonville']});assert.equal(r.event.time,'21:00')});
test('CivicPlus extracts a stated conference room instead of guessing from the meeting name',()=>{const r=extractCivicMeeting({url:'https://www.fayetteville-ar.gov/m/calendar/event/detail/1',fetchedAt:date,text:'Public Meetings Calendar\nTentative: Airport Board\nDoors to the meeting room will open 30 minutes prior to the start of the meeting. Airport Conference Room\nSee More\nPublic Meetings\n2:00 PM - No set end time | Thursday, October 15, 2026\n4500 S. School Ave, Fayetteville AR 72701\nRelated Events\nCity Hall'});assert.equal(r.event.venue,'Airport Conference Room');assert.ok(r.event.research.claims.some(c=>c.field==='venue'&&c.quote==='Airport Conference Room'));assert.ok(r.event.uncertainFields.includes('date'))});
test('unsupported source still needs a human visible-schedule check',()=>{const c=fixture();c.url='https://other.example/event';assert.ok(extractCapturedPage(c,target).event.uncertainFields.includes('source'))});
