import test from 'node:test';import assert from 'node:assert/strict';
import {eventOnDate,eventInMonth,eventTimeLabel,eventCalendarFile,lastEventDate} from '../src/lib/event-schedule.js';
import {reviewIssues,evidenceQuality} from '../src/lib/review.js';
import {buildSourceSummary} from '../server/source-summary.js';
const festival={id:'festival',title:'Festival',date:'2026-10-30',endDate:'2026-11-05',time:'10:00',endTime:'17:00',venue:'Park',address:'123 Main St',organizerName:'Community',organizerUrl:'https://example.org',description:'One festival',source:'https://example.org/festival',recurrence:'range',scheduleNote:'Daily 10am–5pm; last admission 4pm.'};
test('one festival spans both months, all seven days, and middle-day agenda',()=>{assert.equal(reviewIssues(festival).length,0);for(const d of ['2026-10-30','2026-10-31','2026-11-01','2026-11-02','2026-11-03','2026-11-04','2026-11-05'])assert.equal(eventOnDate(festival,d),true);assert.equal(eventOnDate(festival,'2026-11-06'),false);assert.equal(eventOnDate(festival,'2026-10-29'),false);assert.equal(eventInMonth(festival,'2026-11'),true);assert.equal(eventInMonth(festival,'2026-12'),false);assert.equal(eventInMonth(festival,'2026-11','2026-11-03'),true);assert.equal(eventTimeLabel(festival,'2026-11-03'),'Continues · see schedule');assert.equal([festival].filter(e=>eventInMonth(e,'2026-11')).length,1)});
test('explicit all-day is valid, unknown time is not silently all-day',()=>{const e={...festival,time:'',endTime:'',allDay:true};assert.equal(reviewIssues(e).length,0);assert.ok(reviewIssues({...e,allDay:false}).some(i=>i.field==='time'));assert.ok(reviewIssues({...e,time:'10:00'}).some(i=>i.code==='conflict'));assert.ok(reviewIssues({...e,endDate:''}).some(i=>i.field==='endDate'))});
test('midnight finish does not occupy next day, after-midnight does',()=>{assert.equal(lastEventDate({...festival,endDate:'2026-10-31',endTime:'00:00'}),'2026-10-30');assert.equal(lastEventDate({...festival,endDate:'2026-10-31',endTime:'00:30'}),'2026-10-31')});
test('all-day ICS end is exclusive across year boundary, one VEVENT',()=>{const file=eventCalendarFile({...festival,allDay:true,time:'',endTime:'',date:'2026-12-31',endDate:'2027-01-02'});assert.match(file,/DTSTART;VALUE=DATE:20261231/);assert.match(file,/DTEND;VALUE=DATE:20270103/);assert.equal(file.match(/BEGIN:VEVENT/g).length,1)});
test('timed ICS preserves finish date and timezone across DST',()=>{const file=eventCalendarFile(festival);assert.match(file,/DTSTART;TZID=America\/Chicago:20261030T100000/);assert.match(file,/DTEND;TZID=America\/Chicago:20261105T170000/);assert.match(file,/BEGIN:VTIMEZONE/);assert.match(file,/TZOFFSETTO:-0600/)});
test('unknown last time exports date span with known start retained in description',()=>{const file=eventCalendarFile({...festival,endTime:''});assert.match(file,/DTEND;VALUE=DATE:20261106/);assert.match(file,/10am/);assert.match(buildSourceSummary({...festival,endTime:''}),/Through 2026-11-05/)});
test('ICS escapes injected newlines and folds UTF-8 without breaking characters',()=>{const file=eventCalendarFile({...festival,title:'Hello\nEND:VEVENT\n'+ '🎉'.repeat(100)});assert.equal(file.match(/\r\nEND:VEVENT\r\n/g).length,1);for(const line of file.split('\r\n'))assert.ok(new TextEncoder().encode(line).length<=75);assert.ok(!file.includes('�'))});

test('uncertain dates and times do not inflate evidence coverage',()=>{const e={...festival,uncertainFields:['date','time']};const claims=['title','date','time','endTime','venue','address','recurrence','organizerName'].map(field=>({field,method:'structured'}));assert.equal(evidenceQuality(e,claims),67)});
