import test from 'node:test';import assert from 'node:assert/strict';
import worker from '../server/worker.js';import {verifyChallenge} from '../server/spam.js';import {buildSourceSummary} from '../server/source-summary.js';
const request=()=>new Request('https://findout.events/api/events');const env={TURNSTILE_SITE_KEY:'public-test',TURNSTILE_SECRET_KEY:'private-test'};
const answer=(patch={})=>async()=>Response.json({success:true,hostname:'findout.events',action:'submit',...patch});
test('server challenge verifies hostname, action and success; forged/replayed tokens fail',async()=>{await verifyChallenge(request(),env,'valid','submit',answer());for(const patch of [{success:false,'error-codes':['timeout-or-duplicate']},{hostname:'evil.example'},{action:'login'}])await assert.rejects(verifyChallenge(request(),env,'forged','submit',answer(patch)),{status:400});});
test('configured challenge fails closed on outage, missing token or partial configuration',async()=>{await assert.rejects(verifyChallenge(request(),env,'valid','submit',async()=>{throw Error()}),{status:503});await assert.rejects(verifyChallenge(request(),env,'','submit'),{status:400});await assert.rejects(verifyChallenge(request(),{TURNSTILE_SITE_KEY:'key'},'anything','submit'),{status:503});await verifyChallenge(request(),{},undefined,'submit')});
test('edge burst limiter rejects before any database access and supplies retry delay',async()=>{const r=await worker.fetch(request(),{API_READ_BURST:{limit:async()=>({success:false})},DB:{prepare:()=>{throw Error('DB must not be touched')}}});assert.equal(r.status,429);assert.equal(r.headers.get('Retry-After'),'60')});
test('cross-origin POST, unsupported methods, oversized bodies and SQL-like missing fields cannot write',async()=>{let writes=0;const e={DB:{prepare:()=>{writes++;throw Error('No database writes expected')}}};const req=(body,origin='https://findout.events')=>new Request('https://findout.events/api/events',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal((await worker.fetch(req({},'https://evil.example'),e)).status,403);assert.equal((await worker.fetch(new Request('https://findout.events/api/events',{method:'DELETE'}),e)).status,405);assert.equal((await worker.fetch(req({x:'x'.repeat(65000)}),e)).status,413);assert.equal((await worker.fetch(req({title:"'); DROP TABLE events;--",category:'arts'}),e)).status,400);assert.equal(writes,0)});
test('source summary never mixes neighboring events, ticket UI, or private evidence',()=>{const e={title:'American Aquarium',date:'2026-12-07',time:'20:00',venue:"George's Majestic Lounge",evidence:'Private audit note'};const s=buildSourceSummary(e,[{text:"American Aquarium\nDec 7th 8:00PM (Mon)\nDOORS 7:00PM\nGeorge's Majestic Lounge\nPURCHASE\nPURCHASE\nMini Trees\nDec 9th 8:00PM (Wed)\nDOORS 6:00PM"}]);assert.match(s,/Monday, December 7, 2026/);assert.match(s,/Doors 7:00 PM/);assert.doesNotMatch(s,/Mini Trees|PURCHASE|Private|6:00/);assert.doesNotMatch(buildSourceSummary(e,[{text:'Mini Trees\nDOORS 6:00PM\nPURCHASE'}]),/Doors/)});
