PRAGMA foreign_keys=ON;
CREATE TABLE categories(id TEXT PRIMARY KEY,label TEXT NOT NULL UNIQUE);
INSERT INTO categories VALUES ('music','Music & nightlife'),('arts','Arts & making'),('community','Community'),('outdoors','Outdoors & movement'),('food','Food & drink'),('learning','Classes & learning');
CREATE TABLE venues(id TEXT PRIMARY KEY, identity_key TEXT NOT NULL UNIQUE,name TEXT NOT NULL,address TEXT NOT NULL,city TEXT NOT NULL DEFAULT 'Fayetteville',region TEXT NOT NULL DEFAULT 'AR',country TEXT NOT NULL DEFAULT 'US');
CREATE TABLE organizers(id TEXT PRIMARY KEY,identity_key TEXT NOT NULL UNIQUE,name TEXT NOT NULL,url TEXT NOT NULL DEFAULT '',email TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '');
ALTER TABLE events ADD COLUMN venue_id TEXT REFERENCES venues(id);
ALTER TABLE events ADD COLUMN organizer_id TEXT REFERENCES organizers(id);
ALTER TABLE events ADD COLUMN timezone TEXT NOT NULL DEFAULT 'America/Chicago';
ALTER TABLE events ADD COLUMN recurrence TEXT NOT NULL DEFAULT 'unknown' CHECK(recurrence IN ('single','rule','range','unknown'));
ALTER TABLE events ADD COLUMN rrule TEXT NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN uncertain_fields TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(uncertain_fields));
CREATE TABLE event_categories(event_id TEXT NOT NULL REFERENCES events(id),category_id TEXT NOT NULL REFERENCES categories(id),PRIMARY KEY(event_id,category_id));
CREATE INDEX category_events ON event_categories(category_id,event_id);
CREATE TABLE event_occurrences(id TEXT PRIMARY KEY,event_id TEXT NOT NULL REFERENCES events(id),start_date TEXT,start_time TEXT,end_date TEXT,end_time TEXT,timezone TEXT NOT NULL,UNIQUE(event_id));
CREATE INDEX occurrence_dates ON event_occurrences(start_date,start_time,event_id);
CREATE TABLE source_snapshots(id TEXT PRIMARY KEY,source_id TEXT NOT NULL REFERENCES sources(id),url TEXT NOT NULL,fetched_at TEXT NOT NULL,content_hash TEXT NOT NULL,content_text TEXT NOT NULL,fetch_status TEXT NOT NULL CHECK(fetch_status IN ('ok','blocked','error')),UNIQUE(url,content_hash));
CREATE TABLE event_evidence(event_id TEXT NOT NULL REFERENCES events(id),revision INTEGER NOT NULL,field TEXT NOT NULL,snapshot_id TEXT NOT NULL REFERENCES source_snapshots(id),quote TEXT NOT NULL,method TEXT NOT NULL CHECK(method IN ('structured','text','manual','inferred')),PRIMARY KEY(event_id,revision,field,snapshot_id));
CREATE INDEX evidence_event ON event_evidence(event_id,revision);
CREATE TABLE crawl_steps(id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES crawl_runs(id),event_id TEXT REFERENCES events(id),sequence INTEGER NOT NULL,stage TEXT NOT NULL,rule TEXT NOT NULL,outcome TEXT NOT NULL,detail TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE INDEX crawl_steps_run ON crawl_steps(run_id,sequence);
CREATE TABLE moderation_decisions(id TEXT PRIMARY KEY,event_id TEXT NOT NULL REFERENCES events(id),actor_id TEXT NOT NULL REFERENCES users(id),action TEXT NOT NULL CHECK(action IN ('save','approve','reject','remove','enrich')),from_status TEXT NOT NULL,to_status TEXT NOT NULL,from_revision INTEGER NOT NULL,to_revision INTEGER NOT NULL,reason TEXT NOT NULL,before_json TEXT NOT NULL CHECK(json_valid(before_json)),after_json TEXT NOT NULL CHECK(json_valid(after_json)),created_at TEXT NOT NULL,UNIQUE(event_id,to_revision));
CREATE INDEX decisions_event ON moderation_decisions(event_id,to_revision);
CREATE TRIGGER decisions_no_update BEFORE UPDATE ON moderation_decisions BEGIN SELECT RAISE(ABORT,'Decisions are append-only'); END;
CREATE TRIGGER decisions_no_delete BEFORE DELETE ON moderation_decisions BEGIN SELECT RAISE(ABORT,'Decisions are append-only'); END;
CREATE TRIGGER snapshots_no_update BEFORE UPDATE ON source_snapshots BEGIN SELECT RAISE(ABORT,'Evidence snapshots are immutable'); END;
CREATE TRIGGER evidence_no_update BEFORE UPDATE ON event_evidence BEGIN SELECT RAISE(ABORT,'Evidence claims are immutable'); END;
-- Existing flat columns remain a compatibility projection for the public calendar.
INSERT INTO venues SELECT 'legacy:'||MIN(id),lower(trim(venue))||'|'||lower(trim(address)),venue,address,'Fayetteville','AR','US' FROM events WHERE venue<>'' GROUP BY lower(trim(venue)),lower(trim(address));
UPDATE events SET venue_id=(SELECT id FROM venues WHERE identity_key=lower(trim(events.venue))||'|'||lower(trim(events.address)));
INSERT INTO event_categories SELECT id,category FROM events;
INSERT INTO event_occurrences SELECT id,id,NULLIF(date,''),NULLIF(time,''),NULLIF(end_date,''),NULLIF(end_time,''),'America/Chicago' FROM events;
CREATE VIEW analytics_category_status AS SELECT c.id category_id,c.label,e.status,COUNT(*) event_count FROM events e JOIN event_categories ec ON ec.event_id=e.id JOIN categories c ON c.id=ec.category_id GROUP BY c.id,e.status;
CREATE VIEW analytics_review_outcomes AS SELECT actor_id,action,substr(created_at,1,10) day,COUNT(*) decision_count FROM moderation_decisions GROUP BY actor_id,action,day;
