import {buildSourceSummary} from './source-summary.js';
import {verifyChallenge} from './spam.js';
import {evidenceQuality} from '../src/lib/review.js';
import {extendedInput,recordStatements,validateResearch,reviewIssues} from './records.js';
const encoder = new TextEncoder();
const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const hex = b => Array.from(new Uint8Array(b), x => x.toString(16).padStart(2,'0')).join('');
const hash = async s => hex(await crypto.subtle.digest('SHA-256',encoder.encode(s)));
export async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:encoder.encode(salt),iterations:100000,hash:'SHA-256'},key,256));}
const token = () => hex(crypto.getRandomValues(new Uint8Array(32)));
const equal = (a,b) => {let n=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)n|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return n===0;};
class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
const fail=(status,message)=>{throw new HttpError(status,message);};
const sql=(env,s,...args)=>env.DB.prepare(s).bind(...args);
const audit=(env,actor,action,target,details='')=>sql(env,'INSERT INTO audit VALUES(?,?,?,?,?,?)',id(),actor,action,target,details,now());
const json=(body,status=200,extra={})=>Response.json(body,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...extra}});
const mapEvent=e=>{const r={...e,sourceSummary:e.source_summary||'',endTime:e.end_time,endDate:e.end_date,organizerType:e.organizer_type,organizerName:e.organizer_name||'',organizerUrl:e.organizer_url||'',organizerEmail:e.organizer_email||'',organizerPhone:e.organizer_phone||'',uncertainFields:JSON.parse(e.uncertain_fields||'[]')};r.issues=reviewIssues(r);return r;};
const eventSelect="SELECT e.*,o.name organizer_name,o.url organizer_url,o.email organizer_email,o.phone organizer_phone FROM events e LEFT JOIN organizers o ON o.id=e.organizer_id";
async function limit(env,key,max,seconds=3600){const bucket=Math.floor(Date.now()/1000/seconds);const row=await sql(env,'INSERT INTO rate_limits VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 WHERE count < ? RETURNING count',`${key}:${bucket}`,(bucket+1)*seconds,max).first();if(!row)fail(429,'Request limit reached. Please try later.');}
async function body(req){if(!req.headers.get('content-type')?.startsWith('application/json'))fail(415,'JSON required.');const reader=req.body?.getReader();if(!reader)fail(400,'Missing body.');let n=0;const chunks=[];for(;;){const {done,value}=await reader.read();if(done)break;n+=value.length;if(n>64000){await reader.cancel();fail(413,'Request too large.');}chunks.push(value);}const bytes=new Uint8Array(n);let i=0;for(const v of chunks){bytes.set(v,i);i+=v.length;}try{const b=JSON.parse(new TextDecoder().decode(bytes));if(!b||typeof b!=='object'||Array.isArray(b))fail(400,'Object required.');return b;}catch{fail(400,'Invalid JSON.');}}
function text(b,k,max,required=false){const v=b?.[k]??'';if(typeof v!=='string'||v.length>max||(required&&!v.trim()))fail(400,`Invalid ${k}.`);return v.trim();}
function url(value){if(!value)return '';try{const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)throw Error();return u.href;}catch{fail(400,'Source must be an HTTPS URL.');}}
function eventInput(b,complete=false){if(!b||typeof b!=='object'||Array.isArray(b))fail(400,'Event object required.');const e={};for(const [k,n]of [['title',180],['date',10],['time',5],['endTime',5],['endDate',10],['venue',200],['address',300],['category',20],['price',100],['description',3000],['sourceSummary',1400],['source',2000],['evidence',5000]])e[k]=text(b,k,n,['title','category'].includes(k));
if(e.date&&(!/^\d{4}-\d{2}-\d{2}$/.test(e.date)||!Number.isFinite(Date.parse(e.date))||new Date(e.date).toISOString().slice(0,10)!==e.date))fail(400,'Valid date required.');
for(const k of ['time','endTime'])if(e[k]&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(e[k]))fail(400,'Invalid time.');
if(e.endDate&&(!/^\d{4}-\d{2}-\d{2}$/.test(e.endDate)||!Number.isFinite(Date.parse(e.endDate))||new Date(e.endDate).toISOString().slice(0,10)!==e.endDate||e.endDate<e.date))fail(400,'Invalid end date.');
if(!['music','arts','community','outdoors','food','learning'].includes(e.category))fail(400,'Invalid category.');e.source=url(e.source);e.price=e.price||'Check organizer';
try{Object.assign(e,extendedInput(b));}catch(err){fail(400,err.message);}
if(complete&&reviewIssues(e).length)fail(400,'Resolve flagged fields before approval: '+reviewIssues(e).map(i=>i.field).join(', '));
e.score=Number.isInteger(b.score)&&b.score>=0&&b.score<=100?b.score:null;
e.organizerType=['community','business','crawl'].includes(b.organizerType)?b.organizerType:'community';return e;}
async function fingerprint(e){return hash([e.title,e.date,e.time,e.venue].map(v=>v.trim().toLowerCase()).join('|'));}
function insertEvent(env,e,eventId,fp){return sql(env,'INSERT OR IGNORE INTO events(id,title,date,time,end_time,end_date,venue,address,category,price,description,source_summary,source,evidence,score,organizer_type,fingerprint,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',eventId,e.title,e.date,e.time,e.endTime||null,e.endDate||null,e.venue,e.address,e.category,e.price,e.description,e.sourceSummary||'',e.source,e.evidence,e.score,e.organizerType,fp,now(),now());}
async function user(req,env){const raw=(req.headers.get('cookie')||'').match(/(?:^|;\s*)__Host-findout=([a-f0-9]{64})(?:;|$)/)?.[1];if(!raw)return null;return sql(env,'SELECT u.id,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.hash=? AND s.expires>? AND u.enabled=1',await hash(raw),Math.floor(Date.now()/1000)).first();}
async function requireUser(req,env,admin=false){const u=await user(req,env);if(!u)fail(401,'Sign in to manage FindOut!.');if(admin&&u.role!=='admin')fail(403,'Administrator access required.');return u;}
function origin(req){if(req.headers.get('origin')!==new URL(req.url).origin)fail(403,'Submit from this website.');}
async function agent(req,env){const t=req.headers.get('authorization')?.match(/^Bearer ([a-f0-9]{64})$/)?.[1];if(!t)fail(401,'Agent token required.');const a=await sql(env,'SELECT hash,label FROM agent_tokens WHERE hash=? AND enabled=1',await hash(t)).first();if(!a)fail(401,'Invalid agent token.');return a;}
export default {
 async fetch(req,env,ctx){try{return await route(req,env,ctx);}catch(e){if(e.message?.includes('UNIQUE constraint failed: events.fingerprint'))return json({error:'An event with this title, date, time and venue already exists.'},409);if(!e.status)console.error('FindOut request failed',e.name);return json({error:e.status?e.message:'Service temporarily unavailable. Please retry.'},e.status||503,e.status===429?{'Retry-After':'60'}:{});}},
 async scheduled(_,env){await env.DB.batch([sql(env,'DELETE FROM sessions WHERE expires<?',Math.floor(Date.now()/1000)),sql(env,'DELETE FROM rate_limits WHERE expires<?',Math.floor(Date.now()/1000))]);}
};
async function route(req,env,ctx){const p=new URL(req.url).pathname;const method=req.method;
 if(!p.startsWith('/api/'))return env.ASSETS.fetch(req);
 if(!['GET','POST'].includes(method))fail(405,'Method not allowed.');
 if(method==='POST'&&p!=='/api/agent/ingest')origin(req);
 const ip=req.headers.get('cf-connecting-ip')||'local';
 const binding=method==='GET'?env.API_READ_BURST:env.API_WRITE_BURST;
 if(binding&&!(await binding.limit({key:ip})).success)fail(429,'Too many requests. Please wait a minute.');
 if(method==='POST'&&['/api/events','/api/reports','/api/login'].includes(p)&&env.PUBLIC_WRITE_BURST&&!(await env.PUBLIC_WRITE_BURST.limit({key:p+':'+ip})).success)fail(429,'Please wait a minute before trying again.');
 if(p==='/api/config'&&method==='GET')return json({turnstileSiteKey:env.TURNSTILE_SITE_KEY||''});
 if(p==='/api/health'&&method==='GET'){await sql(env,'SELECT 1').first();return json({ok:true,storage:'D1',paidAI:false});}
 if(p==='/api/session'&&method==='GET')return json({user:await user(req,env),adminConfigured:true,aiConfigured:false});
 if(p==='/api/login'&&method==='POST'){await limit(env,'login:'+await hash(req.headers.get('cf-connecting-ip')||'local'),8,900);const b=await body(req),email=text(b,'email',254,true).toLowerCase(),pw=text(b,'password',256,true);const u=await sql(env,'SELECT * FROM users WHERE email=? AND enabled=1',email).first();const derived=await passwordHash(pw,u?.salt||'findout-dummy-salt');if(!u||!equal(derived,u.password_hash))fail(401,'Email or password incorrect.');const t=token();await env.DB.batch([sql(env,'INSERT INTO sessions VALUES(?,?,?)',await hash(t),u.id,Math.floor(Date.now()/1000)+43200),audit(env,u.id,'login',u.id)]);return json({ok:true},200,{'Set-Cookie':`__Host-findout=${t}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200`});}
 if(p==='/api/logout'&&method==='POST'){const raw=(req.headers.get('cookie')||'').match(/__Host-findout=([a-f0-9]{64})/)?.[1];if(raw)await sql(env,'DELETE FROM sessions WHERE hash=?',await hash(raw)).run();return json({ok:true},200,{'Set-Cookie':'__Host-findout=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'});}
 if(p==='/api/events'&&method==='GET'){const cacheKey=new Request(new URL('/api/events',req.url));const cache=globalThis.caches?.default;const hit=await cache?.match(cacheKey);if(hit)return hit;const result=await sql(env,"SELECT e.id,e.title,e.date,e.time,e.end_time,e.end_date,e.venue,e.address,e.category,e.price,e.description,e.source_summary,e.source,e.timezone,e.recurrence,e.rrule,o.name organizer_name,o.url organizer_url,o.email organizer_email,o.phone organizer_phone FROM events e LEFT JOIN organizers o ON o.id=e.organizer_id WHERE e.status='approved' AND e.date>=? AND e.date<=? ORDER BY e.date,e.time LIMIT 2000",new Date(Date.now()-31*86400000).toISOString().slice(0,10),new Date(Date.now()+400*86400000).toISOString().slice(0,10)).all();const response=json({events:result.results.map(r=>{const e=mapEvent(r);delete e.issues;delete e.uncertainFields;return e;})},200,{'Cache-Control':'public, max-age=30'});if(cache&&ctx)ctx.waitUntil(cache.put(cacheKey,response.clone()));return response;}
 if(p==='/api/events'&&method==='POST'){const b=await body(req);if(b.website)fail(400,'Submission rejected.');const e=eventInput(b);for(const k of ['date','time','venue','address','source','description'])if(!e[k])fail(400,'Please supply '+k+'.');await verifyChallenge(req,env,b.turnstileToken,'submit');await limit(env,'submit:'+await hash(ip),5);await limit(env,'public-submissions',200,86400);e.sourceSummary='';e.evidence='Community submission: organizer details not yet verified.';e.score=null;e.organizerType=b.organizerType==='business'?'business':'community';const eventId=id();await env.DB.batch([insertEvent(env,e,eventId,await fingerprint(e)),...await recordStatements(env,e,eventId,1)]);return json({ok:true,message:'Submitted for human review. Not yet published.'},201);}
 if(p==='/api/reports'&&method==='POST'){await limit(env,'report:'+await hash(req.headers.get('cf-connecting-ip')||'local'),5);await limit(env,'public-reports',200,86400);const b=await body(req),eventId=text(b,'eventId',100,true),reason=text(b,'reason',40,true),details=text(b,'details',1500);if(!['incorrect','fake','illegal','cancelled','duplicate','other'].includes(reason))fail(400,'Invalid reason.');if(!await sql(env,"SELECT id FROM events WHERE id=? AND status='approved'",eventId).first())fail(404,'Event not found.');await sql(env,'INSERT INTO reports VALUES(?,?,?,?,?,?)',id(),eventId,reason,details,'open',now()).run();return json({ok:true});}
 if(p==='/api/agent/sources'&&method==='GET'){await agent(req,env);return json({sources:(await sql(env,'SELECT * FROM sources WHERE enabled=1 LIMIT 500').all()).results});}
 if(p==='/api/agent/ingest'&&method==='POST'){
 const a=await agent(req,env);await limit(env,'agent-ingest',120,86400);const b=await body(req);
 if(!Array.isArray(b.events)||b.events.length>20)fail(400,'Send at most 20 candidates per batch.');
 const runId=id(),batch=[sql(env,'INSERT INTO crawl_runs VALUES(?,?,?,?,?)',runId,a.label,text(b,'summary',3000),0,now())],inserts=[];
 for(const input of b.events){const e=eventInput(input);e.organizerType='crawl';let research;try{research=validateResearch(input.research);}catch(err){fail(400,err.message);}e.sourceSummary=e.sourceSummary||buildSourceSummary(e,research?.snapshots||[]);e.score=evidenceQuality(e,research?.claims||[]);const eventId=id();inserts.push(batch.length);batch.push(insertEvent(env,e,eventId,await fingerprint(e)),...await recordStatements(env,e,eventId,1,research,runId));}
 if(batch.length>42)fail(400,'Evidence batch is too large for the free-tier query budget. Send fewer candidates or fewer trace steps.');
 const result=await env.DB.batch(batch),count=inserts.reduce((n,i)=>n+(result[i].meta?.changes||0),0);
 await env.DB.batch([sql(env,'UPDATE crawl_runs SET candidates=? WHERE id=?',count,runId),audit(env,'agent:'+a.label,'ingest',runId,String(count))]);return json({ok:true,inserted:count,status:'pending',runId});}
 if(!p.startsWith('/api/admin/'))fail(404,'Not found.');const u=await requireUser(req,env);await limit(env,'admin:'+u.id,600);
 if(p==='/api/admin/source-summary'&&method==='POST'){
 const b=await body(req),eventId=text(b,'id',100,true),row=await sql(env,eventSelect+' WHERE e.id=?',eventId).first();if(!row)fail(404,'Event not found.');if(row.revision!==b.revision)fail(409,'Event changed. Reload.');
 const snapshots=(await sql(env,'SELECT DISTINCT s.content_text text FROM source_snapshots s JOIN event_evidence v ON v.snapshot_id=s.id WHERE v.event_id=? AND v.revision=?',eventId,b.revision).all()).results;
 const summary=buildSourceSummary(mapEvent(row),snapshots);if(row.source_summary===summary)return json({ok:true,unchanged:true});
 const decisionId=id(),timestamp=now(),next=b.revision+1;
 const result=await env.DB.batch([sql(env,'UPDATE events SET source_summary=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?',summary,timestamp,eventId,b.revision),sql(env,"INSERT INTO moderation_decisions SELECT ?,?,?, 'enrich',?,?,?,?,?,?,?,? WHERE changes()=1",decisionId,eventId,u.id,row.status,row.status,b.revision,next,'Generated public summary from this event and its source capture; publication status preserved.',JSON.stringify(mapEvent(row)),JSON.stringify({...mapEvent(row),sourceSummary:summary,revision:next}),timestamp),sql(env,'INSERT INTO event_evidence SELECT event_id,?,field,snapshot_id,quote,method FROM event_evidence WHERE event_id=? AND revision=? AND EXISTS(SELECT 1 FROM moderation_decisions WHERE id=?)',next,eventId,b.revision,decisionId)]);
 if(!result[0].meta.changes)fail(409,'Event changed. Reload.');await globalThis.caches?.default?.delete(new Request(new URL('/api/events',req.url)));return json({ok:true});
 }
 if(p==='/api/admin/events'&&method==='GET'){const status=new URL(req.url).searchParams.get('status')||'pending';if(!['pending','approved','rejected','removed'].includes(status))fail(400,'Invalid status.');return json({events:(await sql(env,eventSelect+' WHERE e.status=? ORDER BY e.date,e.time LIMIT 1000',status).all()).results.map(mapEvent)});}
 if(p==='/api/admin/event'&&method==='POST'){
 const b=await body(req),eventId=text(b,'id',100,true),previous=await sql(env,eventSelect+' WHERE e.id=?',eventId).first();
 if(!previous)fail(404,'Event not found.');if(b.revision!==previous.revision)fail(409,'Another reviewer changed this event. Reload before saving.');
 const action=text(b,'action',20,true);if(!['save','approve','reject','remove','enrich'].includes(action))fail(400,'Invalid action.');
 if(action==='enrich'&&previous.status!=='pending')fail(409,'Only pending records can be enriched.');
 const status={save:'pending',approve:'approved',reject:'rejected',remove:'removed',enrich:'pending'}[action];
 if(action==='approve'&&b.confirmed!==true)fail(400,'Explicit review confirmation required.');
 const e=eventInput(b.event,action==='approve'),reason=text(b,'reason',1500);let research;try{research=validateResearch(b.event.research);}catch(err){fail(400,err.message);}
 if(research)e.score=evidenceQuality(e,research.claims);
 const oldEvent=mapEvent(previous);if(!e.sourceSummary||(e.sourceSummary===oldEvent.sourceSummary&&(['title','date','time','endTime','venue','address'].some(k=>e[k]!==oldEvent[k])||JSON.stringify(e.uncertainFields)!==JSON.stringify(oldEvent.uncertainFields))))e.sourceSummary=buildSourceSummary(e,research?.snapshots||[]);
 const timestamp=now(),runId=research?id():null,next=b.revision+1,decisionId=id();
 const batch=[sql(env,'UPDATE events SET title=?,date=?,time=?,end_time=?,end_date=?,venue=?,address=?,category=?,price=?,description=?,source_summary=?,source=?,evidence=?,score=?,status=?,fingerprint=?,revision=revision+1,updated_at=?,reviewed_by=?,reviewed_at=? WHERE id=? AND revision=?',e.title,e.date,e.time,e.endTime||null,e.endDate||null,e.venue,e.address,e.category,e.price,e.description,e.sourceSummary||'',e.source,e.evidence,e.score,status,await fingerprint(e),timestamp,action==='enrich'?previous.reviewed_by:u.id,action==='enrich'?previous.reviewed_at:timestamp,eventId,b.revision),
 sql(env,'INSERT INTO moderation_decisions SELECT ?,?,?,?,?,?,?,?,?,?,?,? WHERE changes()=1',decisionId,eventId,u.id,action,previous.status,status,b.revision,next,reason,JSON.stringify(mapEvent(previous)),JSON.stringify({...e,status,revision:next}),timestamp)];
 if(runId)batch.push(sql(env,'INSERT INTO crawl_runs SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM moderation_decisions WHERE id=?)',runId,'assisted-source-review',reason||'Evidence refresh; awaiting human approval.',1,timestamp,decisionId));
 batch.push(...await recordStatements(env,e,eventId,next,research,runId,decisionId));
 // Preserve exact historical evidence; new revisions link to the same immutable snapshots.
 if(!research){const prior=mapEvent(previous),fields=Object.keys(e).filter(k=>e[k]===prior[k]);batch.push(sql(env,`INSERT INTO event_evidence SELECT event_id,?,field,snapshot_id,quote,method FROM event_evidence WHERE event_id=? AND revision=? AND field IN (${fields.map(()=>'?').join(',')}) AND EXISTS(SELECT 1 FROM moderation_decisions WHERE id=?)`,next,eventId,b.revision,...fields,decisionId));}
 if(batch.length>42)fail(400,'Evidence is too large for the free-tier query budget. Reduce duplicate claims or trace steps.');
 const result=await env.DB.batch(batch);if(!result[0].meta.changes)fail(409,'Event changed. Reload.');await globalThis.caches?.default?.delete(new Request(new URL('/api/events',req.url)));return json({ok:true});
 }
 if(p==='/api/admin/evidence'&&method==='GET'){
 const eventId=new URL(req.url).searchParams.get('id');
 return json({snapshots:(await sql(env,'SELECT DISTINCT s.* FROM source_snapshots s JOIN event_evidence v ON v.snapshot_id=s.id JOIN events e ON e.id=v.event_id AND e.revision=v.revision WHERE e.id=?',eventId).all()).results,
 claims:(await sql(env,'SELECT v.* FROM event_evidence v JOIN events e ON e.id=v.event_id AND e.revision=v.revision WHERE e.id=?',eventId).all()).results,
 history:(await sql(env,'SELECT d.*,u.email actor FROM moderation_decisions d JOIN users u ON u.id=d.actor_id WHERE d.event_id=? ORDER BY d.to_revision DESC LIMIT 100',eventId).all()).results,
 legacyHistory:(await sql(env,'SELECT a.*,u.email actor_email FROM audit a LEFT JOIN users u ON u.id=a.actor WHERE a.target=? ORDER BY a.created_at DESC LIMIT 100',eventId).all()).results});}
 if(p==='/api/admin/dashboard'&&method==='GET')return json({counts:(await sql(env,'SELECT status,COUNT(*) count FROM events GROUP BY status').all()).results,categories:(await sql(env,'SELECT * FROM analytics_category_status').all()).results,openReports:(await sql(env,"SELECT COUNT(*) count FROM reports WHERE status='open'").first()).count});
 if(p==='/api/admin/reports'&&method==='GET')return json({reports:(await sql(env,'SELECT r.*, e.title FROM reports r JOIN events e ON e.id=r.event_id ORDER BY r.created_at DESC LIMIT 500').all()).results});
 if(p==='/api/admin/reports'&&method==='POST'){const b=await body(req),reportId=text(b,'id',100,true);await env.DB.batch([sql(env,"UPDATE reports SET status='resolved' WHERE id=?",reportId),audit(env,u.id,'resolve_report',reportId)]);return json({ok:true});}
 if(p==='/api/admin/sources'&&method==='GET')return json({sources:(await sql(env,'SELECT * FROM sources ORDER BY name LIMIT 500').all()).results});
 if(p==='/api/admin/sources'&&method==='POST'){const b=await body(req),sourceId=text(b,'id',100)||id(),name=text(b,'name',200,true),sourceUrl=url(text(b,'url',2000,true)),notes=text(b,'notes',3000);await env.DB.batch([sql(env,'INSERT INTO sources VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,url=excluded.url,enabled=excluded.enabled,notes=excluded.notes',sourceId,name,sourceUrl,b.enabled===false||b.enabled==='false'?0:1,notes),audit(env,u.id,'save_source',sourceId)]);return json({ok:true});}
 if(p==='/api/admin/audit'&&method==='GET')return json({audit:(await sql(env,"SELECT d.id,u.email actor,d.action,d.event_id target,d.created_at,d.from_status,d.to_status,d.from_revision,d.to_revision,d.reason FROM moderation_decisions d JOIN users u ON u.id=d.actor_id UNION ALL SELECT a.id,COALESCE(u.email,a.actor),a.action,a.target,a.created_at,NULL,NULL,NULL,NULL,a.details FROM audit a LEFT JOIN users u ON u.id=a.actor ORDER BY 5 DESC LIMIT 200").all()).results});
 if(p==='/api/admin/runs'&&method==='GET')return json({runs:(await sql(env,'SELECT * FROM crawl_runs ORDER BY created_at DESC LIMIT 100').all()).results,steps:(await sql(env,'SELECT s.* FROM crawl_steps s JOIN (SELECT id FROM crawl_runs ORDER BY created_at DESC LIMIT 100) r ON r.id=s.run_id ORDER BY s.created_at,s.sequence LIMIT 2000').all()).results});
 if(p==='/api/admin/export'&&method==='GET'){if(u.role!=='admin')fail(403,'Administrator required.');return json({exportedAt:now(),events:(await sql(env,eventSelect+' ORDER BY e.date LIMIT 10000').all()).results,sources:(await sql(env,'SELECT * FROM sources LIMIT 500').all()).results,reports:(await sql(env,'SELECT * FROM reports LIMIT 5000').all()).results});}
 if(p==='/api/admin/password'&&method==='POST'){const b=await body(req),current=text(b,'current',256,true),pw=text(b,'password',256,true);if(pw.length<16)fail(400,'Use at least 16 characters.');const row=await sql(env,'SELECT * FROM users WHERE id=?',u.id).first();if(!equal(await passwordHash(current,row.salt),row.password_hash))fail(403,'Current password incorrect.');const salt=token();await env.DB.batch([sql(env,'UPDATE users SET password_hash=?,salt=? WHERE id=?',await passwordHash(pw,salt),salt,u.id),sql(env,'DELETE FROM sessions WHERE user_id=?',u.id),audit(env,u.id,'change_password',u.id)]);return json({ok:true});}
 if(u.role!=='admin')fail(403,'Administrator required.');
 if(p==='/api/admin/users'&&method==='GET')return json({users:(await sql(env,'SELECT id,email,role,enabled,created_at FROM users').all()).results});
 if(p==='/api/admin/users'&&method==='POST'){const b=await body(req);if(b.id){if(b.id===u.id)fail(400,'Cannot disable your own account.');await env.DB.batch([sql(env,'UPDATE users SET enabled=? WHERE id=?',b.enabled===false?0:1,text(b,'id',100,true)),sql(env,'DELETE FROM sessions WHERE user_id=?',b.id),audit(env,u.id,'set_user_enabled',b.id)]);return json({ok:true});}const email=text(b,'email',254,true).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(400,'Invalid email.');const pw=text(b,'password',256,true);if(pw.length<16)fail(400,'Use at least 16 characters.');const userId=id(),salt=token();await env.DB.batch([sql(env,'INSERT INTO users VALUES(?,?,?,?,?,?,?)',userId,email,'moderator',await passwordHash(pw,salt),salt,1,now()),audit(env,u.id,'create_moderator',userId)]);return json({ok:true});}
 if(p==='/api/admin/tokens'&&method==='GET')return json({tokens:(await sql(env,'SELECT hash,label,enabled,created_at FROM agent_tokens').all()).results});
 if(p==='/api/admin/tokens'&&method==='POST'){const b=await body(req);if(b.revoke){await env.DB.batch([sql(env,'UPDATE agent_tokens SET enabled=0 WHERE hash=?',text(b,'revoke',64,true)),audit(env,u.id,'revoke_agent',b.revoke)]);return json({ok:true});}const t=token(),h=await hash(t),label=text(b,'label',100,true);await env.DB.batch([sql(env,'INSERT INTO agent_tokens VALUES(?,?,1,?)',h,label,now()),audit(env,u.id,'create_agent',h)]);return json({token:t,message:'Copy now. This token can only read enabled sources and submit pending candidates.'});}
 fail(404,'Not found.');
}
