import {useEffect,useState,FormEvent} from 'react';
import {toast} from 'sonner';
import {api,Session} from './workflows';
import {categories,CalEvent} from '@/lib/events';
type EventRecord=CalEvent & {revision:number;endDate?:string;evidence?:string;score?:number;status:string};
type Row=Record<string,any>;
const safeLink=(s:string)=>s.startsWith('https://')?s:undefined;
function Fields({value,onChange,review=true}:{value:Row;onChange:(v:Row)=>void;review?:boolean}){return <div className="manage-fields">{[['title','Title','text'],['date','Date','date'],['time','Start time (Central)','time'],['endTime','End time','time'],['endDate','Series end date (clear for one occurrence)','date'],['venue','Venue','text'],['address','Street address · Fayetteville, AR','text'],['price','Price / eligibility','text'],['source','Source URL','url']].filter(([key])=>review||key!=='endDate').map(([key,label,type])=><label key={key}>{label}<input type={type} value={value[key]||''} maxLength={key==='source'?2000:300} onChange={e=>onChange({...value,[key]:e.target.value})}/></label>)}<label>Category<select value={value.category||'community'} onChange={e=>onChange({...value,category:e.target.value})}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{(review?['description','evidence']:['description']).map(key=><label className="wide" key={key}>{key==='description'?'Public description':'Review evidence / uncertainty'}<textarea value={value[key]||''} maxLength={key==='evidence'?5000:3000} onChange={e=>onChange({...value,[key]:e.target.value})}/></label>)}</div>}
function Review({event,reload}:{event:EventRecord;reload:()=>void}){const [draft,setDraft]=useState<Row>(event),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false);async function save(action:string){setBusy(true);try{await api('admin/event',{id:event.id,revision:event.revision,event:draft,action,confirmed});toast.success(action==='approve'?'Published to the calendar.':'Saved.');reload();}catch(e){toast.error((e as Error).message);}finally{setBusy(false)}}return <details className="manage-card"><summary><strong>{event.title}</strong><span>{event.date} · {event.time||'Time unconfirmed'} · {event.score??'—'}/100</span></summary><p>{event.venue} · {event.organizerType}</p>{event.source&&<a href={safeLink(event.source)} target="_blank" rel="noopener noreferrer">Check original source ↗</a>}<p>{event.evidence}</p><Fields value={draft} onChange={setDraft}/><label className="confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked the source, date, time, Fayetteville location and description.</label><div className="manage-actions"><button disabled={busy||!confirmed} className="primary" onClick={()=>save('approve')}>Approve & publish</button><button disabled={busy} className="secondary" onClick={()=>save('save')}>Save as pending</button><button disabled={busy} className="secondary" onClick={()=>save('reject')}>Reject</button>{event.status==='approved'&&<button disabled={busy} className="secondary" onClick={()=>save('remove')}>Unpublish</button>}</div></details>}
export default function Manage({onChanged}:{onChanged:()=>void}){const [session,setSession]=useState<Session|null>(null),[tab,setTab]=useState('events'),[status,setStatus]=useState('pending'),[data,setData]=useState<Row>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[newToken,setNewToken]=useState('');
async function loadSession(){try{setSession(await api<Session>('session'))}catch(e){setError((e as Error).message)}}
async function load(){try{setError('');setData(await api<Row>(`admin/${tab}${tab==='events'?'?status='+status:''}`));}catch(e){setError((e as Error).message)}}
useEffect(()=>{void loadSession()},[]);useEffect(()=>{if(session?.user&&tab!=='account')void load()},[session,tab,status]);
async function submit(e:FormEvent<HTMLFormElement>,path:string){e.preventDefault();const f=e.currentTarget;setBusy(true);try{const payload=Object.fromEntries(new FormData(f));const result=await api<Row>(path,payload);if(path==='login')await loadSession();else if(path==='admin/password'){toast.success('Password changed. Sign in again.');setSession(null);await loadSession();}else{if(result.token)setNewToken(result.token);f.reset();void load();toast.success('Saved.');}}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
async function change(path:string,b:Row){try{await api(path,b);void load();toast.success('Saved.')}catch(e){toast.error((e as Error).message)}}
if(!session?.user)return <form className="event-form" onSubmit={e=>submit(e,'login')}><p>Administrator and moderator sign-in. Browsing and community submissions need no account.</p>{error&&<div role="alert">{error}</div>}<label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><button className="primary" disabled={busy}>Sign in</button></form>;
const admin=session.user.role==='admin';return <div className="management"><div className="manage-actions"><span>{session.user.email} · {session.user.role}</span><button className="secondary" onClick={async()=>{await api('logout',{});await loadSession()}}>Sign out</button></div><nav className="manage-tabs">{['events','reports','sources','runs','audit',...(admin?['users','tokens']:[]),'account'].map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>{setTab(t);setData({});setError('')}}>{({events:'Events',reports:'Reports',sources:'Sources',runs:'Crawl runs',audit:'History',users:'Moderators',tokens:'Local agents',account:'Account'} as Row)[t]}</button>)}</nav>{error&&<div className="notice" role="alert">{error}<button onClick={load}>Retry</button></div>}
{tab==='events'&&<><div className="manage-actions"><select aria-label="Review status" value={status} onChange={e=>setStatus(e.target.value)}>{['pending','approved','rejected','removed'].map(s=><option key={s}>{s}</option>)}</select><span>{data.events?.length??0} records · changes are saved online</span><button className="secondary" onClick={load}>Refresh</button></div>{data.events?.map((e:EventRecord)=><Review key={e.id+':'+e.revision} event={e} reload={()=>{void load();onChanged()}}/>)}{data.events?.length===0&&<p>No events in this queue.</p>}</>}
{tab==='reports'&&data.reports?.map((r:Row)=><div className="manage-card" key={r.id}><strong>{r.title}</strong><p>{r.reason}: {r.details}</p><small>{r.status}</small>{r.status==='open'&&<button className="secondary" onClick={()=>change('admin/reports',{id:r.id})}>Mark resolved</button>}</div>)}
{tab==='sources'&&<><p>Enabled sources are available to the local crawler. Adding a source does not start a crawl.</p>{data.sources?.map((s:Row)=><details className="manage-card" key={s.id}><summary>{s.name} · {s.enabled?'Enabled':'Disabled'}</summary><form className="event-form" onSubmit={e=>submit(e,'admin/sources')}><input name="id" type="hidden" value={s.id}/><input name="enabled" type="hidden" value={s.enabled?'true':'false'}/><input name="name" aria-label="Source name" defaultValue={s.name}/><input name="url" aria-label="Source URL" defaultValue={s.url} type="url"/><textarea name="notes" aria-label="Source notes" defaultValue={s.notes}/><button className="secondary">Save edits</button><button type="button" className="secondary" onClick={()=>change('admin/sources',{...s,enabled:!s.enabled})}>{s.enabled?'Disable':'Enable'}</button></form></details>)}<form className="event-form" onSubmit={e=>submit(e,'admin/sources')}><h3>Add source</h3><input name="name" placeholder="Source name" aria-label="New source name" required/><input name="url" type="url" placeholder="https://…" aria-label="New source URL" required/><textarea name="notes" placeholder="Crawl notes" aria-label="New source notes"/><button className="primary" disabled={busy}>Add source</button></form></>}
{tab==='runs'&&<><p>Crawlers submit candidates for human review; they cannot publish.</p>{data.runs?.map((r:Row)=><div className="manage-card" key={r.id}><strong>{r.agent} · {r.candidates} added</strong><p>{r.summary}</p><small>{r.created_at}</small></div>)}</>}
{tab==='audit'&&data.audit?.map((a:Row)=><p key={a.id}><small>{a.created_at}</small><br/>{a.action} · {a.target}</p>)}
{tab==='users'&&<>{data.users?.map((u:Row)=><p key={u.id}>{u.email} · {u.role} · {u.enabled?'Active':'Disabled'}{u.id!==session.user?.id&&<button className="secondary" onClick={()=>change('admin/users',{id:u.id,enabled:!u.enabled})}>{u.enabled?'Disable':'Enable'}</button>}</p>)}<form className="event-form" onSubmit={e=>submit(e,'admin/users')}><h3>Add moderator</h3><input name="email" type="email" aria-label="Moderator email" placeholder="Email" required/><input name="password" type="password" minLength={16} maxLength={256} autoComplete="new-password" placeholder="Temporary password (16+ characters)" aria-label="Moderator temporary password" required/><p>Share credentials privately. Moderators can change their password under Account.</p><button className="primary" disabled={busy}>Create moderator</button></form></>}
{tab==='tokens'&&<><p>Tokens allow reading enabled sources and sending pending candidates only. Keep them on your local Mac.</p>{data.tokens?.map((t:Row)=><p key={t.hash}>{t.label} · {t.enabled?'Active':'Revoked'}{!!t.enabled&&<button className="secondary" onClick={()=>change('admin/tokens',{revoke:t.hash})}>Revoke</button>}</p>)}<form className="event-form" onSubmit={e=>submit(e,'admin/tokens')}><input name="label" placeholder="M2 mini" aria-label="Agent name" required/><button className="primary" disabled={busy}>Create agent token</button></form>{newToken&&<div className="notice"><p>Copy now; it will not be shown again.</p><textarea aria-label="New agent token" readOnly value={newToken}/><button onClick={()=>setNewToken('')}>Hide token</button></div>}</>}
{tab==='account'&&<><form className="event-form" onSubmit={e=>submit(e,'admin/password')}><label>Current password<input name="current" type="password" autoComplete="current-password" required/></label><label>New password<input name="password" type="password" minLength={16} maxLength={256} autoComplete="new-password" required/></label><button className="primary" disabled={busy}>Change password & sign out</button></form>{admin&&<button className="secondary" onClick={async()=>{try{const r=await api('admin/export');const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));a.href=url;a.download='findout-export.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){toast.error((e as Error).message)}}}>Export event data</button>}</>}
</div>}
export {Fields};
