import {Challenge} from './challenge';
import Manage,{Fields} from './manage';
'use client';
import {useEffect,useState,FormEvent} from 'react';
import {Check,ShieldCheck,Search,ExternalLink,Loader2,RefreshCw,Share2,Flag,Download,MapPin,Clock,CalendarDays,Sparkles,LockKeyhole} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {toast} from 'sonner';
import {categories,CalEvent,timeLabel} from '@/lib/events';
export type Session={user:{id:string;name:string;email:string;role:string}|null;adminConfigured:boolean;aiConfigured:boolean};
export async function api<T=Record<string,unknown>>(path:string,payload?:unknown):Promise<T>{
 const res=await fetch('/api/'+path,{method:payload===undefined?'GET':'POST',credentials:'same-origin',headers:payload===undefined?{}:{'Content-Type':'application/json'},body:payload===undefined?undefined:JSON.stringify(payload),cache:'no-store'});
 const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed.');return data as T;
}
function Choice({name,value,onChange,items}:{name:string;value:string;onChange:(v:string)=>void;items:{value:string;label:string}[]}){return <Select name={name} value={value} onValueChange={onChange}><SelectTrigger className="form-select"><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem value={i.value} key={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>}
export function Submission({session,onDone}:{session:Session|null;onDone:()=>void}){
 const [draft,setDraft]=useState<Record<string,any>>({category:'community',organizerType:'community'}),[busy,setBusy]=useState(false),[challengeToken,setChallengeToken]=useState(''),[challengeReset,setChallengeReset]=useState(0);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await api('events',{...draft,turnstileToken:challengeToken});toast.success('Submitted for review. Thank you!');onDone();}catch(e){toast.error((e as Error).message)}finally{setBusy(false);setChallengeReset(n=>n+1)}}
 return <form className="event-form" onSubmit={submit}><p>Share a public event in Fayetteville, Arkansas. A moderator checks every submission before it appears.</p><label>Submitting as<select value={draft.organizerType} onChange={e=>setDraft({...draft,organizerType:e.target.value})}><option value="community">Community member</option><option value="business">Business / organizer</option></select></label><Fields value={draft} onChange={setDraft} review={false}/><label className="honeypot" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={draft.website||''} onChange={e=>setDraft({...draft,website:e.target.value})}/></label><p>No email or account is required. Please include a source link and any age or registration requirements.</p><Challenge reset={challengeReset} onToken={setChallengeToken}/><button className="primary" disabled={busy}>{busy?'Submitting…':'Submit for review'}</button></form>;
}
export function EventDetails({event,session}:{event:CalEvent;session:Session|null}){
 const [report,setReport]=useState(false),[reason,setReason]=useState('incorrect'),[busy,setBusy]=useState(false);const c=categories.find(c=>c.id===event.category)!;
 async function share(){const url=new URL('/fayetteville',document.baseURI);url.searchParams.set('event',event.id);try{if(navigator.share)await navigator.share({title:event.title,url:url.href});else {await navigator.clipboard.writeText(url.href);toast.success('Event link copied.');}}catch(e){if((e as Error).name!=='AbortError')toast.error('Could not share. Copy the address from your browser.');}}
 function download(){const clean=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;').replace(/\r/g,'');const start=event.date.replaceAll('-','')+'T'+event.time.replace(':','')+'00';const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//FindOut!//Community Calendar//EN','BEGIN:VEVENT',`UID:${event.id}@findout.events`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').split('.')[0]}Z`,`DTSTART;TZID=America/Chicago:${start}`,...(event.endTime?[`DTEND;TZID=America/Chicago:${(event.endDate||event.date).replaceAll('-','')}T${event.endTime.replace(':','')}00`]:[]),`SUMMARY:${clean(event.title)}`,`LOCATION:${clean(event.venue+' '+(event.address||''))}`,`DESCRIPTION:${clean(event.description)}`,'END:VEVENT','END:VCALENDAR'];const blob=new Blob([lines.join('\r\n')+'\r\n'],{type:'text/calendar;charset=utf-8'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='findout-event.ics';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}

 return <div className="event-detail"><span className="category-tag" style={{background:c.bg,color:c.color}}>{c.name}</span>{event.sample&&<div className="notice">This is an illustrative event, not a real listing. Please don’t travel to it.</div>}<p className="event-description">{event.description}</p>{event.sourceSummary&&event.sourceSummary!==event.description&&<p className="event-source-summary"><strong>From the source</strong><br/>{event.sourceSummary}</p>}<div className="detail-info"><CalendarDays/><span>{new Date(event.date+'T12:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</span></div><div className="detail-info"><Clock/><span>{timeLabel(event.time)}{event.endTime&&<> – {timeLabel(event.endTime)}</>} · Central Time</span></div><div className="detail-info"><MapPin/><span>{event.venue}<small>{event.address||'Address unconfirmed'}</small></span></div><div className="detail-info"><ShieldCheck/><span>{event.organizerName||'Organizer unconfirmed'}{event.organizerUrl&&<small><a href={event.organizerUrl} target="_blank" rel="noopener noreferrer">Organizer website ↗</a></small>}</span></div><div className="detail-cost">{event.price}<small>Check with the organizer for availability.</small></div><div className="detail-actions"><button className="primary" onClick={share}><Share2 size={16}/>Share event</button><button className="secondary" disabled={event.sample} onClick={download}><Download size={16}/>Add to calendar</button></div>{event.source&&<a className="source-link" href={event.source} target="_blank" rel="noopener noreferrer">View original source <ExternalLink size={14}/></a>}<button className="source-link" onClick={()=>setReport(!report)}><Flag size={14}/>Report an issue</button>{report&&<form className="event-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const form=new FormData(e.currentTarget);await api('reports',{eventId:event.id,reason,details:form.get('details')});toast.success('Report sent for review.');setReport(false)}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}}><label>Reason<select value={reason} onChange={e=>setReason(e.target.value)}>{['incorrect','fake','illegal','cancelled','duplicate','other'].map(r=><option key={r}>{r}</option>)}</select></label><label>Details<textarea name="details" maxLength={1500}/></label><button className="secondary" disabled={busy}>Send report</button></form>}</div>
}
export function Moderator({session,onChanged}:{session:Session|null;onChanged:()=>void}){return <Manage onChanged={onChanged}/>;}
